name: Run Test Workflow

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  process_files:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Checkout the repository

    # Build Docker image
    - name: Build the Docker image
      run: docker build -t gemini_ex/gha_gemi .

    # Run the Docker container and process .txt files
    - name: Docker Run Action
      run: |
        # Ensure the required directories and files are in place
        mkdir -p /root/output

        # Loop through each .txt file in the openjur_docs/ folder and process with Gemini
        for file in $GITHUB_WORKSPACE/openjur_docs/*.txt; do
          echo "Processing $file"

          # Run the Gemini API with the appropriate prompt
          docker run --rm --name gha_gemi --env API_KEY="${{ secrets.API_KEY }}" \
            -v $GITHUB_WORKSPACE/scripts/:/root/scripts/:rw \
            -v $GITHUB_WORKSPACE/prompts/:/root/prompts/:rw \
            -v $GITHUB_WORKSPACE/config/:/root/config/:rw \
            -v $GITHUB_WORKSPACE/output:/root/output:rw \
            gemini_ex/gha_gemi R -e 'Sys.setenv("PATH" = paste(Sys.getenv("PATH"),"/usr/local/stata/",sep=":")); source("~/scripts/run.R")' \
            -v $file:/root/text.txt  # Pass the current .txt file into the Docker container
        done

    # Upload the Gemini results as an artifact
    - uses: actions/upload-artifact@v4
      with:
        name: gemini_results
        path: ${{ github.workspace }}/output/
